# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
# images: ['gcr.io/$PROJECT_ID/hello_npm']

steps:
- name: gcr.io/$PROJECT_ID/skaffold:alpha
  args: ['run', '-f=skaffold.yaml' ,'--default-repo=gcr.io/vertob']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_SKAFFOLD_PATH}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_SKAFFOLD_PROFILE}'
  # - 'CLOUDSDK_SKAFFOLD_PATH=${_SKAFFOLD_PATH}'
  # - 'CLOUDSDK_SKAFFOLD_PROFILE=[_SKAFFOLD_PROFILE]'

# steps:
# - name: 'ubuntu'
#   args: ['echo', 'hello ${_SUB_VALUE} ${_SUB_PATH} ${_FAVORITE_COLOR}']
# substitutions:
#     _SUB_VALUE: world
# options:
#     substitution_option: 'ALLOW_LOOSE'