steps:
- name: gcr.io/$PROJECT_ID/skaffold:alpha
  args: ['run', '-f=skaffold.yaml' ,'--default-repo=gcr.io/$PROJECT_ID']
  env:
  - 'SKAFFOLD_PATH=${_SKAFFOLD_PATH}'
  - 'SKAFFOLD_PROFILE=${_SKAFFOLD_PROFILE}'