# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
# images: ['gcr.io/$PROJECT_ID/hello_npm']
steps:
- name: gcr.io/$PROJECT_ID/skaffold:alpha
  args: ['run', '-f=skaffold-merchant/skaffold.yaml']